### ISSUE TITLE
Proposal: Change of prefix

### ISSUE THREAD

**Issue by shawntanzk** [brain-bican/bican_application_ontology#2]
Current prefix is BAO, this is however taken already:
https://bioregistry.io/registry/bao

Given its an application ontology, and we will have our own purl, its not SUPER important, but while nothing is in here yet, could I propose we change the prefix. Bioregistery suggest avoiding 2-3 letter prefixes too. 
Suggestions:
bicano
bicao

**Comment by patrick-lloyd-ray** [comment]
Yeah, I guess we should avoid any (potential) clashes just in case. 

I like `bicano`.
